### ISSUE TITLE
extendMode

### ISSUE THREAD

**Issue by josealeonf** [Tigrov/yii2-kendoui#1]
the option `'extendMode' => true` always crashes, cannot read the extraFields

> PHP Recoverable Error 'yii\base\ErrorException' with message 'Argument 1 passed to yii\base\Model::toArray() must be of the type array, null given, called in /../_protected/vendor/tigrov/yii2-kendoui/actions/Read.php on line 62 and defined'

**Comment by Tigrov** [comment]
Hi, try it now.

**Comment by josealeonf** [comment]
Yes, it shows the fields now, thanks.
